version: "3.7"

services:
  db:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
  server:
    container_name: key-server
    depends_on:
      - db
    image: node:latest
    working_dir: /root/api
    volumes:
      - ./:/root/api
    entrypoint: bash -c "yarn start"
    ports:
      - 30021:30021

